### ISSUE TITLE
Do we want to split GitHub actions into different files?

### ISSUE THREAD

**Issue by domna** [nomad-coe/nomad-parser-nexus#43]
Since we had some problems with pylinting I thought we could split our GitHub actions into separate files. This would at least ensure that all tests will be run for every commit. Especially in a branch it's nice to see if the tests are failing or not and to do pylinting minor issues at the end. The drawbacks are that the complete testing set will be a little slower (as there need to be several similar envs to be created) and I think we would also take more actions time from GitHub (I don't know if we're tight there but probably not).

@sanbrock @shabihsherjeel @aalbino2 @mkuehbach @cmmngr 
I could just rewrite the actions, I just wanted to gather your opinions on if we should do it. What do you think?

**Comment by rettigl** [comment]
There is also the option to make all the linting actions to continue on fail, and only the tests cause a fail of the pipeline. Off course then you have to manually look into the output to see if there are linting issues.

**Comment by domna** [comment]
Thanks for pointing it out. I just updated that the tests always run even if previous steps failed in PR #39.
