### ISSUE TITLE
Installation dependency h5py missing

### ISSUE THREAD

**Issue by mkuehbach** [nomad-coe/nomad-parser-nexus#5]
Tested the installation documentation on Win11 inside a WSL2 running Ubuntu 20.04.3 LTS.
Parser installed successfully in the local virtualenvironment but throwed upon execution python -m ...
With ModuleNotFoundError: No module named h5py
After fixing this via a pip install h5py throws 

File "/home/mkuehbach/GITHUB/parser-nexus/nexusparser/parser.py", line 25, in <module>
    from nomad.datamodel.metainfo import nexus
ImportError: cannot import name 'nexus' from 'nomad.datamodel.metainfo' 
(/home/mkuehbach/GITHUB/.mynomadcoe/lib/python3.9/site-packages/nomad/datamodel/metainfo/__init__.py) 

After installing tests successfully, pytest -sv tests throws the same above missing nexus issue.

**Comment by shabihsherjeel** [comment]
I have updated the docs to show that you need the package nexusparser to be installed. 

For this import error, you can comment it for the data converter and this should rid you of the block. But this has to eventually be fixed in the nexusparser.

**Comment by mkuehbach** [comment]
pip install nomad-lab=1.0.0 and
setting export PYTHONPATH= to the location of <prefix>/parsernexus solved it in a dirty manner
