### ISSUE TITLE
Compressed data entries shouldn't be handled later with links

### ISSUE THREAD

**Issue by shabihsherjeel** [nomad-coe/nomad-parser-nexus#68]
The compression implementation right now is handled after all fields in the template are processed once just like the links. This is needed for links because we need to make sure what we are linking to already exists. But in the case of compression if the compressed dataset has an attribute, the dataset is created as a group and the attribute is written to the group. This shouldn't be the case. The compressed dataset should be written right away and then the attribute will be added accordingly.

Possible attempts to fix this:

- The check for whether we are handling links should be better. `... and if "links" in data.keys():` 
https://github.com/nomad-coe/nomad-parser-nexus/blob/e812e769f220ff21d9713a6d88ebb5b814897249/nexusutils/dataconverter/writer.py#L241
- The code for writing and handling compressed datasets should be moved from here, https://github.com/nomad-coe/nomad-parser-nexus/blob/e812e769f220ff21d9713a6d88ebb5b814897249/nexusutils/dataconverter/writer.py#L143, to here, https://github.com/nomad-coe/nomad-parser-nexus/blob/e812e769f220ff21d9713a6d88ebb5b814897249/nexusutils/dataconverter/writer.py#L243.

**Comment by sanbrock** [comment]
Note that "link"s are fine to be put to the second pass, but "shape"s are tricky.  
a) a VDS can only be made if the main dataset is already there, so it has to be put to the 2nd pass, or rather  
b) only after links are also created, so a 3rd pass is needed, where dependency resolution shall also be applied.  
Also note,  
c) a VDS may be decorated with its own attributes those need to be processed together with the VDS to avoid the main problem of this issue

**Comment by shabihsherjeel** [comment]
We could add links and VDS to their respective dicts in the first run and handle them accordingly.

**Comment by shabihsherjeel** [comment]
Fixed with 93b2eae
